version: '3.9'
services:
    selenium-hub:
        image: selenium/hub:4.0.0
        ports:
            - "4442-4444:4442-4444"
    selenium-chrome:
        image: selenium/node-chrome:4.0.0
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443